require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe EasesController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # Ease. As you add validations to Ease, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # EasesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all eases as @eases" do
      ease = Ease.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:eases)).to eq([ease])
    end
  end

  describe "GET show" do
    it "assigns the requested ease as @ease" do
      ease = Ease.create! valid_attributes
      get :show, {:id => ease.to_param}, valid_session
      expect(assigns(:ease)).to eq(ease)
    end
  end

  describe "GET new" do
    it "assigns a new ease as @ease" do
      get :new, {}, valid_session
      expect(assigns(:ease)).to be_a_new(Ease)
    end
  end

  describe "GET edit" do
    it "assigns the requested ease as @ease" do
      ease = Ease.create! valid_attributes
      get :edit, {:id => ease.to_param}, valid_session
      expect(assigns(:ease)).to eq(ease)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Ease" do
        expect {
          post :create, {:ease => valid_attributes}, valid_session
        }.to change(Ease, :count).by(1)
      end

      it "assigns a newly created ease as @ease" do
        post :create, {:ease => valid_attributes}, valid_session
        expect(assigns(:ease)).to be_a(Ease)
        expect(assigns(:ease)).to be_persisted
      end

      it "redirects to the created ease" do
        post :create, {:ease => valid_attributes}, valid_session
        expect(response).to redirect_to(Ease.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved ease as @ease" do
        post :create, {:ease => invalid_attributes}, valid_session
        expect(assigns(:ease)).to be_a_new(Ease)
      end

      it "re-renders the 'new' template" do
        post :create, {:ease => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested ease" do
        ease = Ease.create! valid_attributes
        put :update, {:id => ease.to_param, :ease => new_attributes}, valid_session
        ease.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested ease as @ease" do
        ease = Ease.create! valid_attributes
        put :update, {:id => ease.to_param, :ease => valid_attributes}, valid_session
        expect(assigns(:ease)).to eq(ease)
      end

      it "redirects to the ease" do
        ease = Ease.create! valid_attributes
        put :update, {:id => ease.to_param, :ease => valid_attributes}, valid_session
        expect(response).to redirect_to(ease)
      end
    end

    describe "with invalid params" do
      it "assigns the ease as @ease" do
        ease = Ease.create! valid_attributes
        put :update, {:id => ease.to_param, :ease => invalid_attributes}, valid_session
        expect(assigns(:ease)).to eq(ease)
      end

      it "re-renders the 'edit' template" do
        ease = Ease.create! valid_attributes
        put :update, {:id => ease.to_param, :ease => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested ease" do
      ease = Ease.create! valid_attributes
      expect {
        delete :destroy, {:id => ease.to_param}, valid_session
      }.to change(Ease, :count).by(-1)
    end

    it "redirects to the eases list" do
      ease = Ease.create! valid_attributes
      delete :destroy, {:id => ease.to_param}, valid_session
      expect(response).to redirect_to(eases_url)
    end
  end

end
